package giuliacrepaldi.Lanzi_Orto_Urbano_Management.enums;

public enum TypeActivity {
    FRUTTA_E_VERDURA,
    MINI_MARKET,
    NEGOZIO,
    FIORERIA,
    BAR_CON_CUCINA,
    BAR_SENZA_CUCINA,
    PASTICCERIA,
    PASTICCERIA_VEGANA,
    PASTICCERIA_VEGETARIANA,
    GROSSISTI_DI_FRESCHI_E_FRESCHISSIMI,
    HOTEL_CON_CUCINA,
    HOTEL_SENZA_CUCINA,
    RISTORANTE,
    RISTORANTE_ETNICO,
    RISTORANTE_VEGANO,
    RISTORANTE_VEGETARIANO,
    LIBERI_PROFESSIONISTI
}
