spring.application.name=Lanzi-Orto-Urbano-Management
spring.config.import=file:env.properties
server.port=${PORT}
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET}
spring.data.web.pageable.page-serialization-mode=via-dto
#ADMIN
admin.default.email=${ADMIN_EMAIL}
admin.default.password=${ADMIN_PASSWORD}
admin.default.name=${ADMIN_NAME}
admin.default.surname=${ADMIN_SURNAME}
# CLOUDINARY
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_API_SECRET}
#RESEND
resend.api-key=${RESEND.API-KEY}
#COOKIE
cookie.secure=false
#PAYMENT-NEXI
nexi.api-key=${NEXI.API-KEY}
nexi.alias=${NEXI.ALIAS}
nexi.gruppo=${NEXI.GRUPPO}